std_msgs/Float64[] qc               # 6
std_msgs/Float64[] dqc              # 6
std_msgs/Float64[] qt               # 6
std_msgs/Float64[] dqt              # 6

PointOnImg pt                       # tool com
PointOnImg pg                       # goal com
PointOnImg po                       # occlusion com

std_msgs/Float64 area_g
std_msgs/Float64 area_o

PointOnImg[] pg_seg               # 4 points of goal segmentation
PointOnImg[] po_seg               # 4 points of obstacle segmentation
---

std_msgs/Float64[] dqc_next         # 6