//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IbvsControl
{
    [Serializable]
    public class CameraParamMsg : Message
    {
        public const string k_RosMessageName = "ibvs_control/CameraParam";
        public override string RosMessageName => k_RosMessageName;

        public Std.Int64Msg width;
        //  camera resolution (width)
        public Std.Int64Msg height;
        //  camera resolution (height)
        public Std.Float64Msg fx;
        //  f/Sx  (camera focal length)/(sensor width)
        public Std.Float64Msg fy;
        //  f/Sy  (camera focal length)/(sensor height)
        public Std.Float64Msg cx;
        //  Ox/Sx (optic axis interaction point width pos)/(sensor width)
        public Std.Float64Msg cy;
        //  Oy/Sy (optic axis interaction point height pos)/(sensor height)

        public CameraParamMsg()
        {
            this.width = new Std.Int64Msg();
            this.height = new Std.Int64Msg();
            this.fx = new Std.Float64Msg();
            this.fy = new Std.Float64Msg();
            this.cx = new Std.Float64Msg();
            this.cy = new Std.Float64Msg();
        }

        public CameraParamMsg(Std.Int64Msg width, Std.Int64Msg height, Std.Float64Msg fx, Std.Float64Msg fy, Std.Float64Msg cx, Std.Float64Msg cy)
        {
            this.width = width;
            this.height = height;
            this.fx = fx;
            this.fy = fy;
            this.cx = cx;
            this.cy = cy;
        }

        public static CameraParamMsg Deserialize(MessageDeserializer deserializer) => new CameraParamMsg(deserializer);

        private CameraParamMsg(MessageDeserializer deserializer)
        {
            this.width = Std.Int64Msg.Deserialize(deserializer);
            this.height = Std.Int64Msg.Deserialize(deserializer);
            this.fx = Std.Float64Msg.Deserialize(deserializer);
            this.fy = Std.Float64Msg.Deserialize(deserializer);
            this.cx = Std.Float64Msg.Deserialize(deserializer);
            this.cy = Std.Float64Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.width);
            serializer.Write(this.height);
            serializer.Write(this.fx);
            serializer.Write(this.fy);
            serializer.Write(this.cx);
            serializer.Write(this.cy);
        }

        public override string ToString()
        {
            return "CameraParamMsg: " +
            "\nwidth: " + width.ToString() +
            "\nheight: " + height.ToString() +
            "\nfx: " + fx.ToString() +
            "\nfy: " + fy.ToString() +
            "\ncx: " + cx.ToString() +
            "\ncy: " + cy.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
