std_msgs/Int64 width        # camera resolution (width)
std_msgs/Int64 height       # camera resolution (height)

std_msgs/Float64 fx         # f/Sx  (camera focal length)/(sensor width)
std_msgs/Float64 fy         # f/Sy  (camera focal length)/(sensor height)
std_msgs/Float64 cx         # Ox/Sx (optic axis interaction point width pos)/(sensor width)
std_msgs/Float64 cy         # Oy/Sy (optic axis interaction point height pos)/(sensor height)

