//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IbvsControl
{
    [Serializable]
    public class OptimIBVSResponse : Message
    {
        public const string k_RosMessageName = "ibvs_control/OptimIBVS";
        public override string RosMessageName => k_RosMessageName;

        public Std.Float64Msg[] dqc_next;
        //  6

        public OptimIBVSResponse()
        {
            this.dqc_next = new Std.Float64Msg[0];
        }

        public OptimIBVSResponse(Std.Float64Msg[] dqc_next)
        {
            this.dqc_next = dqc_next;
        }

        public static OptimIBVSResponse Deserialize(MessageDeserializer deserializer) => new OptimIBVSResponse(deserializer);

        private OptimIBVSResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.dqc_next, Std.Float64Msg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.dqc_next);
            serializer.Write(this.dqc_next);
        }

        public override string ToString()
        {
            return "OptimIBVSResponse: " +
            "\ndqc_next: " + System.String.Join(", ", dqc_next.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
